name: Docker Build/Publish Image 
on:  
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ secrets.MY_DOCKER_REGISTRY }}
      DOCKER_IMAGE: zwaveme
      DOCKER_TARGET_PLATFORM: linux/arm32v7
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Repository
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
              
